// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK7F47l73Yd2Mqt89fjHdsdA3pRIwxAn0',
    appId: '1:113569386471:web:a18e0b1bc8f705b9e07742',
    messagingSenderId: '113569386471',
    projectId: 'mynotes-flutter-project-atp',
    authDomain: 'mynotes-flutter-project-atp.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-atp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1V35LYaFGFXI1OKbHRbhGBabydWyAuU',
    appId: '1:113569386471:android:f9ecc772ea25789be07742',
    messagingSenderId: '113569386471',
    projectId: 'mynotes-flutter-project-atp',
    storageBucket: 'mynotes-flutter-project-atp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-GJmq5XCaXDh01wYCzm100Rx0ska2ofE',
    appId: '1:113569386471:ios:f73fdca77be0b559e07742',
    messagingSenderId: '113569386471',
    projectId: 'mynotes-flutter-project-atp',
    storageBucket: 'mynotes-flutter-project-atp.appspot.com',
    iosClientId: '113569386471-3j9388fdbonp7dgg2pu3632g37l4dhva.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-GJmq5XCaXDh01wYCzm100Rx0ska2ofE',
    appId: '1:113569386471:ios:f73fdca77be0b559e07742',
    messagingSenderId: '113569386471',
    projectId: 'mynotes-flutter-project-atp',
    storageBucket: 'mynotes-flutter-project-atp.appspot.com',
    iosClientId: '113569386471-3j9388fdbonp7dgg2pu3632g37l4dhva.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
