class DatabaseAlreadyOpenException implements Exception{}
class UnableToGetDocumentsDirectory implements Exception{}
class DatabaseNotOpenException implements Exception{}
class CouldNotDeleteUser implements Exception{}
class UserAlreadyExists implements Exception{}
class CouldNotGetUser implements Exception{}
class CouldNotDeleteNote implements Exception{}
class CouldNotGetNote implements Exception{}
class CouldNotUpdateNote implements Exception{}
class UserShouldBeSetBeforeReadingNotes implements Exception{}